version: "3"
services:
  mysql:
    container_name: project-mysql
    image: "mysql:latest"
    restart: always
    hostname: localhost
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'projects'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: yes

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=mysql
      - DB_ADDR=mysql-keycloak
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_DATABASE=keycloak
    depends_on:
      - mysql-keycloak
      
  mysql-task:
    container_name: task-mysql
    image: "mysql:latest"
    restart: always
    hostname: localhost
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: 'tasks'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: yes    

  mysql-keycloak:
    container_name: task-keycloak
    image: "mysql:latest"
    restart: always
    hostname: localhost
    ports:
      - 3310:3306
    environment:
      MYSQL_DATABASE: 'keycloak'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: yes  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql-keycloak  
      MYSQL_ROOT_PASSWORD: password  
    ports:
      - "8082:80"
    depends_on:
      - mysql-keycloak
  redis:
    image: redis:latest
    restart: always
    container_name: redis_container
    ports:
      - "6379:6379"    
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - 3128:2181
  kafkaserver:
    image: wurstmeister/kafka:latest
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=dresses:1:1,ratings:1:1
    depends_on:
      - zookeeper
  kafka-manager:
    image: hlebalbau/kafka-manager:latest
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: zookeeper:2181
    depends_on:
      - zookeeper
      - kafkaserver