version: "3"
services:
  mysql:
    container_name: project-mysql
    image: "mysql:latest"
    restart: always
    hostname: localhost
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'projects'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
  rabbitmq:
    image: 'rabbitmq:3.13.0-management'
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=my_vhost  # Устанавливаем виртуальный хост
      - RABBITMQ_DEFAULT_EXCHANGE_TYPE=direct
    ports:
      - 15672:15672
      - 5672:5672
  mysql-task:
    container_name: task-mysql
    image: "mysql:latest"
    restart: always
    hostname: localhost
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: 'tasks'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: yes    